### ISSUE TITLE
Nimbus t8n performance issues

### ISSUE THREAD

**Issue by winsvega** [status-im/nimbus-eth1#1558] opened 2023-04-23 16:03 UTC
Nimbus t8n just got super slow recently (~1/2 weeks I guess)

The bug somewhere in cycles. Especially noticeable in stQuadraticComplexityTest

**Comment by AdamSpitz** [comment] 2023-04-24 10:40
Sorry about that. I'm trying to get my stateless-mode stuff merged in
before I leave; it's very possible that there'll be performance
regressions. I can look into it, but I'm running out of time and I'm not
super-productive lately (which is part of the reason why I'm leaving).

I asked Zahary whether I should merge this stuff in even though it's not
really ready yet, and he said yes; maybe I shouldn't?

**Closed** 2023-09-25 13:19 UTC
Labels: optimization
